apiVersion: v1
kind: Secret
metadata:
  name: cnrs-network-config-overlay
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap/package-overlays
stringData:
  cnrs-network-config-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"config-network"}, "kind": "ConfigMap"})
    ---
    data:
      #@overlay/match missing_ok=True
      default-external-scheme: https
      #@overlay/match missing_ok=True
      http-protocol: "Redirected"
      #@overlay/match missing_ok=True
      auto-tls: Enabled

