#@ load("@ytt:data", "data")

#@ if/end "testing-pipeline" not in data.values.excluded_templates:
---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: techdocs-pipeline
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  healthRule:
    singleConditionType: Ready

  params: 
    - name: techdocs_pipeline_matching_labels
      default: 
        apps.tanzu.vmware.com/pipeline: techdocs
  ytt: |
    #@ load("@ytt:data", "data")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def merged_tekton_params():
    #@   params = []
    #@   if hasattr(data.values, "params") and hasattr(data.values.params, "techdocs_pipeline_matching_labels"):
    #@     for param in data.values.params["techdocs_pipeline_matching_labels"]:
    #@       params.append({ "name": param, "value": data.values.params["techdocs_pipeline_matching_labels"][param] })
    #@     end
    #@   end
    #@   params.append({ "name": "source-url", "value": data.values.source.url })
    #@   params.append({ "name": "source-revision", "value": data.values.source.revision })
    #@   params.append({ "name": "component-name", "value": data.values.workload.metadata.name})
    #@   return params
    #@ end
    ---
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: #@ "techdocs-"+data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "test" })
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName

      runTemplateRef:
        name: tekton-source-pipelinerun
        kind: ClusterRunTemplate

      selector:
        resource:
          apiVersion: tekton.dev/v1beta1
          kind: Pipeline

        #@ not hasattr(data.values, "techdocs_pipeline_matching_labels") or fail("techdocs_pipeline_matching_labels param is required")
        matchingLabels: #@ data.values.params["techdocs_pipeline_matching_labels"] or fail("techdocs_pipeline_matching_labels param cannot be empty")

      inputs: 
        tekton-params: #@ merged_tekton_params()
