apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: techdocs-tekton-pipeline
  namespace: canary
  labels:
    apps.tanzu.vmware.com/pipeline: techdocs     # (!) required
spec:
  params:
    - name: source-url                        # (!) required
    - name: source-revision                   # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: gradle:8.0.2-jdk11
            script: |-
              #!/bin/bash -x
              echo "I am the techdocs plugin"
              ls -la
              pwd
              