---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: custom-certs
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: custom-certs
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-sync"
    kapp.k14s.io/change-rule.3: "delete before deleting tanzu-sync"
spec:
  serviceAccountName: sync-sa
  fetch:
    - inline:
        paths:
          cert-and-delegation.yaml: |
            ---
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-contour-cluster-issuer
            spec:
              acme:
                email: cdelashmutt@vmware.com
                privateKeySecretRef:
                  name: acme-account-key
                server: https://acme-v02.api.letsencrypt.org/directory
                solvers:
                - dns01:
                    route53:
                      region: us-east-2
                      hostedZoneID: Z058827839E1KJS2IN09B
            ---
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: default-cert
              namespace: default
              annotations:
                kapp.k14s.io/change-group: certificate
                kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
                kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
            spec:
              commonName: "*.foo.workshop.amer.end2end.link"
              dnsNames:
              - "*.foo.workshop.amer.end2end.link"
              duration: 2160h0m0s
              issuerRef:
                kind: ClusterIssuer
                name: letsencrypt-contour-cluster-issuer
              privateKey:
                algorithm: RSA
                encoding: PKCS1
                size: 2048
              renewBefore: 360h0m0s
              secretName: default-cert
              subject:
                organizations:
                - vmware
            ---
            apiVersion: secretgen.carvel.dev/v1alpha1
            kind: SecretExport
            metadata:
              name: default-cert
              namespace: default
              annotations:
                kapp.k14s.io/change-group: certificate
                kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
                kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
            spec:
              toNamespaces:
              - '*'
            ---
            apiVersion: projectcontour.io/v1
            kind: TLSCertificateDelegation
            metadata:
              name: default-cert
              namespace: default
              annotations:
                kapp.k14s.io/change-group: certificate
                kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
                kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
            spec:
              delegations:
              - secretName: default-cert
                targetNamespaces:
                - "*"
  template:
    - ytt:
        paths: 
        - .
  deploy:
    - kapp: {}