---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-overlay
  namespace: tap-install
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "cert-manager"}})
    ---
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::377668981663:role/workshop-cert-manager
    ---
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-contour-cluster-issuer
      annotations:
        kapp.k14s.io/change-group: certificate
        kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
        kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
    spec:
      acme:
        email: cdelashmutt@vmware.com
        privateKeySecretRef:
          name: acme-account-key
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
        - dns01:
            route53:
              region: us-east-2
              hostedZoneID: Z058827839E1KJS2IN09B
    ---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: default-cert
      namespace: default
      annotations:
        kapp.k14s.io/change-group: certificate
        kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
        kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
    spec:
      commonName: #@ "*.{}".format(data.values.shared.ingress_domain)
      dnsNames:
      - #@ "*.{}".format(data.values.shared.ingress_domain)
      duration: 2160h0m0s
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-contour-cluster-issuer
      privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 2048
      renewBefore: 360h0m0s
      secretName: default-cert
      subject:
        organizations:
        - vmware
    ---
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretExport
    metadata:
      name: default-cert
      namespace: default
      annotations:
        kapp.k14s.io/change-group: certificate
        kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
        kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
    spec:
      toNamespaces:
      - '*'
    ---
    apiVersion: projectcontour.io/v1
    kind: TLSCertificateDelegation
    metadata:
      name: default-cert
      namespace: default
      annotations:
        kapp.k14s.io/change-group: certificate
        kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
        kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
    spec:
      delegations:
      - secretName: default-cert
        targetNamespaces:
        - "*"