apiVersion: ENC[AES256_GCM,data:2aOcQjCVf8Q2OUx7HF/ffMekv9B+xj9Nezf18g==,iv:rnSpIJmtJuuRxpUN2YnI37xUF0ZnI6C88nKQB6VujN0=,tag:SFMvGtyjpaTMxAxFMvp64w==,type:str]
kind: ENC[AES256_GCM,data:L23PNrqsTt4YQeSzen4=,iv:oeXTlUJ6sBtLYPI1W7w9u5fzh2pc61rcdQodp3gb5M8=,tag:sEf8W1W7ol4u9vzdyP3MRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kKqhYWvyQk7JNxuky6MLKlOw7Fk=,iv:6C57sY4gvQL5i+wPTf3br38Qdx0JGSRLgzEasZPmY4U=,tag:IHzukSSQmfbGPDIyNrihYQ==,type:str]
    namespace: ENC[AES256_GCM,data:/ecYGOoN7+YiVZk=,iv:TbXks+l4zbGilt8FPs666soTuu+aVl7uKRmokZ1+GYg=,tag:TXtkO0DmBJeFAC0JeZ2AVA==,type:str]
spec:
    rules:
        - targetNamespaces:
            nameSelector:
                matchNames:
                    - ENC[AES256_GCM,data:ag==,iv:JALF94UiWfXEFB5p50ErgsPAaLld9GhrR7o7GC+GF/M=,tag:09tZnVj8AOwhCa4z1gwHqg==,type:str]
          copyAuthorization:
            #ENC[AES256_GCM,data:E4w3RiP0BKN8ImiAI8Sw9ZAZGGDl4+yvsY3EDJ5J,iv:lqNUOFNk2buQfdrBQwO182BCgBtrsTm3UPidXoWv+bI=,tag:DJ3r2ebNADJwuVI2XlHdlg==,type:comment]
            sharedSecret: ENC[AES256_GCM,data:8KcfsOAHnBWnYmIzZGLmzMRjX0EsgkaslC8IhcQEU9I/Isgd,iv:2wyEI8cUG0QZ2+fblkEnmBY5/jcShvcLanSjAsTvrTM=,tag:mDIX3rwmwka+yM3dCZae9w==,type:str]
          targetSecret:
            name: ENC[AES256_GCM,data:E9+774wj4LPD56rIQqE=,iv:8M6yoEdSB4AfIiVRnHjar3rBxvgD3hZuLEGypHEOXRE=,tag:YYMa1XtUY/2ksI5mAGmaEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0jq2plycmkw4l38aak9cth6v4xvn3wp0kgyj0m0da086ygv2clstfn25y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SG15TG1CVGhKNXBKQUxE
            bXFoVUgyVi85RTRuQ25sNEVTbVE0bCtOUFRRCkFFWEhKdDZJeWdwVkdudzRFM3Rj
            SU0rZWhmZkNubUxNQzBSUlYwSUVaOU0KLS0tIGQwUG9UaGNDL2dkVkxGQXVLb3c4
            cll4RmVpdFlrOUpMWmh2dWo4TGUwKzQKXggGsp+2I3zQqsne3B5/JzerB3nujc0N
            zLmELHerbONzj1vP1TfKCYNuVFGQ6a5xyYZdd7rkcMmOD0Ti6EmXng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T16:04:27Z"
    mac: ENC[AES256_GCM,data:WxY7tWFKlBqC2xX0ERrL33fAqNfb+9KT/0cmZI1R0JlD32xOJ12+L7Q4u1fz379i4yTfEF61ps2uswBAlj2Swc04RqPA5FtH+brfOPCFMC086MJgIN50+feAthiamiKEWkputjx45DUCiJn7nyHo/G95MgHILT81AobgxYPrP5M=,iv:l2OkwHnEdXQTkMdalFJ5APRhHMtVEuF8Mo/2o1rRudU=,tag:F9oQscvsx9lASk/JBZorMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
