---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-secrets.apps.tanzu.vmware.com
  namespace: tap-install
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: external-secrets.apps.tanzu.vmware.com
    versionSelection:
      constraints: ">0.6 <1.0"