---
apiVersion: v1
kind: Secret
metadata:
  name: learningcenter-overlay
  namespace: tap-install
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition", "metadata": {"name": "trainingportals.learningcenter.tanzu.vmware.com"}})
    ---
    spec:
      versions:
      #@overlay/match by="name"
      - name: v1beta1
        additionalPrinterColumns:
        - description: Owner short name
          jsonPath: .metadata.labels.waas/owner-email-prefix
          name: Owner
          priority: 1
          type: string
        - description: Expiry
          jsonPath: .metadata.annotations.janitor/expires
          name: Expires
          priority: 1
          type: string

