#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  annotations:
    kapp.k14s.io/change-group: tanzu-academy-portal
    kapp.k14s.io/change-rule.contour: "upsert after upserting waas-catalog"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    kapp.k14s.io/update-strategy: always-replace
  name: tanzu-academy
spec:
  portal:
    registration:
      type: one-step
      enabled: false
    clients:
      robot:
        id: #@ data.values.tanzu_academy_portal.clients.robot.id
        secret: #@ data.values.tanzu_academy_portal.clients.robot.secret
    credentials:
      admin:
        password: #@ data.values.tanzu_academy_portal.credentials.admin.password
        username: #@ data.values.tanzu_academy_portal.credentials.admin.username
      robot:
        password: #@ data.values.tanzu_academy_portal.credentials.robot.password
        username: #@ data.values.tanzu_academy_portal.credentials.robot.username
    theme:
      frame:
        ancestors:
          - https://tanzu.academy
          - https://*.tanzu.academy
          - https://labs.tanzu.academy
          - https://*.labs.tanzu.academy
          - https://laratanzu.valet
          - https://tanzu.valet
          - https://*.fixeldev.com
          - https://*.tanzuacademy.fixeldev.com
          - http://localhost:8080
  workshops:
    - capacity: 20
      expires: 60m
      name: cartographer-workshop
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: function-workshop
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: lab-container-basics
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: lab-getting-started-with-carvel
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: lab-spring-boot-k8s-gs
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: scc-workshop-dev
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: tap-carvel-workshop
      orphaned: 20m
      reserved: 2
    - capacity: 20
      expires: 60m
      name: tap-overview
      orphaned: 20m
      reserved: 2
