#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: default-cert
  namespace: waas-portal
spec:
  fromNamespace: default
---
apiVersion: v1
kind: Secret
type: servicebinding.io/oauth2
metadata:
  name: waas-portal-values
  namespace: waas-portal
stringData:
  client-id: #@ data.values.waas_portal.client_id
  client-secret: #@ data.values.waas_portal.client_secret
  issuer-uri: https://myvmware.workspaceair.com/SAAS/auth
  provider: workspaceair
  scope: openid, email, profile, user
  type: oauth2
  user-info-uri: https://myvmware.workspaceair.com/SAAS/jersey/manager/api/userinfo
---
apiVersion: v1
kind: Secret
type: servicebinding.io/oauth2
metadata:
  name: broadcom-prod-values
  namespace: waas-portal
stringData:
  client-id: #@ data.values.waas_portal.broadcom_client_id
  client-secret: #@ data.values.waas_portal.broadcom_client_secret
  issuer-uri: https://broadcom.okta.com/oauth2/default
  provider: okta
  scope: openid, email, profile
  type: oauth2
  #!user-info-uri: https://broadcom.okta.com/oauth2/v1/userinfo
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: waas
  namespace: waas-portal
  labels:
    apps.tanzu.vmware.com/workload-type: web-custom-hostname
    app.kubernetes.io/part-of: waas
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      url: https://github.com/Tanzu-Solutions-Engineering/waas-portal.git
      ref:
        branch: main
  serviceClaims:
  - name: workspaceair
    ref:
      apiVersion: v1
      kind: Secret
      name: waas-portal-values
  - name: broadcom-prod
    ref:
      apiVersion: v1
      kind: Secret
      name: broadcom-prod-values
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: custom-hostname
      value: waas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-portal
rules:
- apiGroups:
  - learningcenter.tanzu.vmware.com
  - training.educates.dev
  resources:
  - trainingportals
  - workshops
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-portal-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-portal
subjects:
- kind: ServiceAccount
  name: default
  namespace: waas-portal
