apiVersion: ENC[AES256_GCM,data:OOM=,iv:AcWFfrqaNQTJI7SZBLRJSHYGkVEY4Wtt4d7ncnKlioc=,tag:S6ezgW7xmj95GP+z73pHxQ==,type:str]
kind: ENC[AES256_GCM,data:hY2Yhd7e,iv:N6gcp8xQweHPRIA6/InhDFt9p7HEqzoSceZMJB+AHyE=,tag:NGD9EikQYBWbN1Kh4+G92g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WB4H6ZqVmUuwkgKZznt/hePyIH4=,iv:1qnfgzBBLmCQLkk7uH9dWXP5j3kOCj/CIwfZm/R/tl0=,tag:GAA9tKBwfMvMb++sWv8IbA==,type:str]
    namespace: ENC[AES256_GCM,data:udDb3s/RraFUodQ=,iv:stHnRoqca9amb/S5rYneobApfx+Zz3E+KxlF79gApHU=,tag:GrdQkIHzZcPcjfJMrvnotQ==,type:str]
type: ENC[AES256_GCM,data:kS5FBDvt6e6qLQYfDUnTUyfoeqmUJYr5Hizj2n7g,iv:ze1SfDVxbmHAg9NJnTHYRNW7p5v6TfPlqFA/dPAi214=,tag:6fx8IfJT2Sxv3M4eGmDFUg==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:JmiKIQBgBPVqFgGRpNHMSbsmVMFDLmib3cI6uEk3TCJlP1nsJ9Hd4a/mr9GCGihj+byV/ZRg79DqCzapyJjFdJEiGy/g2BE73avrvHCfUSQayz+1ST5T/W5toUnSWDpDhYk0jVHXBcfB0Q==,iv:YwE+zOrfCrh2JZmOSLx9RqeCu8XybUtuC2oLhxypBpQ=,tag:J2Xi1XwD9LVbOMG/LPrPmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0jq2plycmkw4l38aak9cth6v4xvn3wp0kgyj0m0da086ygv2clstfn25y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VmF3NlpsRzBLOW1Wb3Iz
            Y0ptWGdwVXZtN293TS81cVBIMlpFcnA0QXk4CkMzUVlMQTR6a3dhTU90bFpYV2lE
            Y1gxWkl1Ri8vcDd5dUdnLzZONEVWRHMKLS0tIFhNUjE2d3NkKysvZ3hvWFllaFJD
            N1hEWU1ReXVOUzBnS3Y5V25CTXRadW8K44twK8mONwi0Ib6fqd0hZHM9LzuIH1v3
            77JQOEUs2rcFbUIouPnfTfhs+wzN9RbS9eLG++3ZmMpQPKSKNPkzTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-01T19:08:18Z"
    mac: ENC[AES256_GCM,data:GEeQFjJ3toYBDPQPpObye8yiTwLmcAHoiQAegkOQpqH4slhCXeS2YEVrt8llcOOpxI79XEUO5yqM98au96qwvYbedBLZsj7Jw034jnuwp/FbFzZdzdADy0+BkIDH13oR95L+kJZG6mv6bUQRnJHn6HrcAKPKFxpqClYkAecmh+U=,iv:FagTVp43Dk8afOvGd5oYBdwkJ3V06wEA5YcZj1kNgv4=,tag:N1LmRf4FG67Y/HW0YId3/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
