---
tap_install:
  values:
    profile: full
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - ootb-delivery-basic.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'
    appliveview_connector:
      backend:
        host: appliveview.view.amer.end2end.link
        ingressEnabled: true
    shared:
      ingress_domain: view.amer.end2end.link
      ingress_issuer: letsencrypt-contour-cluster-issuer
      image_registry:
        project_path: registry.gcp.ellin.net/tap/tbs

    appliveview:
      ingressEnabled: true
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/appref-view/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/common/namespaces/dev-namespace
          url: https://github.com/tanzu-end-to-end/e2e-tap-gitops.git
        path: _ytt_lib/dev-namespace-setup
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-auth-overlay
        namespace: tap-install
        create_export: true

    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    accelerator:
      ingress:
        include: true
        enable_tls: true

    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      registry:
        server: "registry.gcp.ellin.net"
        repository: "tap/supply-chain"
      gitops:
        commit_strategy: pull_request
        branch: test
        repository_owner: tanzu-end-to-end
        server_address: https://github.com
        ssh_secret: git-https
        pull_request:
          commit_branch: supply-chain
          server_kind: github
          pull_request_title: Ready for review
          pull_request_body: Pull Request by TAP

    # namespace_provisioner:
    #   controller: false
    #   gitops_install:
    #     ref: origin/main
    #     subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespaces
    #     url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
    #   additional_sources:
    #     - git:
    #         ref: origin/main
    #         subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespace-resources
    #         url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
    #       path: _ytt_lib/namespace-resources
    #   import_data_values_secrets:
    #     - name: workload-git-auth
    #       namespace: tap-install
    #       create_export: true
    #   overlay_secrets:
    #     - name: workload-git-auth-overlay
    #       namespace: tap-install
    #       create_export: true

    contour:
      envoy:
        service:
          type: LoadBalancer

   # cnrs:
   #   default_tls_secret: contour-tls/tls
   #   domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/cpage-pivotal/spring-sensors/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cpage-pivotal/tanzu-java-web-app/blob/main/catalog-info.yaml
            - type: url
              target: https://github.com/tanzu-end-to-end/acme-catalog/blob/main/catalog-info.yaml
        techdocs:
          builder: 'external'
          publisher:
            type: 'awsS3'
            awsS3:
              bucketName: e2e-tap-appref-techdocs
              region: us-east-2
        backend:
          csp:
            default-src: ["'self'"]
            base-uri: ["'self'"]
            font-src: ['self', "https:", "data:"]
            form-action: ['self']
            frame-ancestors: ['self']
            img-src: ['self', 'data:']
            object-src: ["'none'"]
            script-src: ["'self'"]
            script-src-attr: ["'none'"]
            style-src: ["'self'", "https:", "'unsafe-inline'"]
            
          baseUrl: https://tap-gui.view.amer.end2end.link
          cors:
            origin: https://tap-gui.view.amer.end2end.link

 

    metadata_store:
      app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
      ns_for_export_app_cert: "*"

    

    scanning:
      metadataStore:
        url: "" # Disable embedded integration since it's deprecated

    grype:
      namespace: "default" # (optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"

    package_overlays:
    - name:  cert-manager
      secrets:
      - name: cert-manager-overlay
    - name: tap-gui
      secrets:
      - name: tapgui-manager-overlay
    - name: ootb-supply-chain-testing-scanning
      secrets:
      - name: supply-chain-overlay
