---
tap_install:
  values:
    profile: full
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    shared:
      ingress_domain: appref.e2e.ellin.net
      ingress_issuer: ""
      image_registry:
        project_path: registry.gcp.ellin.net/tap/tbs

    buildservice:
      kp_default_repository: "registry.gcp.ellin.net/tap/build"

    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: contour-tls
        secret_name: tls

    appliveview:
      ingressEnabled: true
      tls:
        namespace: contour-tls
        secretName: tls

    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      registry:
        server: "registry.gcp.ellin.net"
        repository: "tap/supply-chain"
      gitops:
        commit_strategy: pull_request
        branch: test
        server_address: "no"
        repository_owner: "none"
        ssh_secret: git-https
        pull_request:
          commit_branch: supply-chain
          server_kind: github
          pull_request_title: Ready for review
          pull_request_body: Pull Request by TAP

    # namespace_provisioner:
    #   controller: false
    #   gitops_install:
    #     ref: origin/main
    #     subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespaces
    #     url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
    #   additional_sources:
    #     - git:
    #         ref: origin/main
    #         subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespace-resources
    #         url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
    #       path: _ytt_lib/namespace-resources
    #   import_data_values_secrets:
    #     - name: workload-git-auth
    #       namespace: tap-install
    #       create_export: true
    #   overlay_secrets:
    #     - name: workload-git-auth-overlay
    #       namespace: tap-install
    #       create_export: true

    contour:
      envoy:
        service:
          type: LoadBalancer

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      tls:
        namespace: contour-tls
        secretName: tls
      app_config:
        app:
          baseUrl: https://tap-gui.appref.e2e.ellin.net
        catalog:
          locations:
            - type: url
              target: https://github.com/cpage-pivotal/spring-sensors/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cpage-pivotal/tanzu-java-web-app/blob/main/catalog-info.yaml
        backend:
          baseUrl: https://tap-gui.appref.e2e.ellin.net
          cors:
            origin: https://tap-gui.appref.e2e.ellin.net
        proxy:
          /metadata-store:
            target: https://metadata-store-app.metadata-store:8443/api/v1
            changeOrigin: true
            secure: false
        kubernetes:
          serviceLocatorMethod:
            type: 'multiTenant'
        # techdocs:
        #   builder: 'external'
        #   publisher:
        #     type: 'awsS3'
        #     awsS3:
        #       bucketName: e2e-tap-techdocs
        #       credentials:
        #         roleArn: arn:aws:iam::377668981663:role/ReadTapTechdocs

    metadata_store:
      app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
      ns_for_export_app_cert: "*"

    scanning:
      metadataStore:
        url: "" # Disable embedded integration since it's deprecated

    grype:
      namespace: "default" # (optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"
