apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-contour-overlay
  namespace: tap-install
stringData:
  workload-git-auth-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"HTTPProxy", "metadata": {"name":"tap-guwi"}}),expects="1+"
    ---
    spec:
      #@overlay/match missing_ok=True
      virtualhost:
        #@overlay/match missing_ok=True
        corsPolicy:
          allowOrigin:
          - "*" 
          allowMethods:
          - GET
          - POST
          - OPTIONS
          allowHeaders:
          - authorization
          - cache-control
          exposeHeaders:
          - Content-Length
          - Content-Range
          maxAge: "10m" 
