apiVersion: v1
kind: Secret
metadata:
  name: workload-git-auth-overlay
  namespace: tap-install
stringData:
  workload-git-auth-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount","metadata":{"name":"default"}}), expects="0+"
    ---
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::377668981663:role/appref1-write-techdocs
    #@overlay/match missing_ok=True    
    secrets:
    #@overlay/append
    - name: git-ssh
    - name: git-https
