#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

#@ def config():
git:
      host: github.com
      username: username
      password: password
      ssh_privatekey: #@ data.values.GIT_SSH_PRIVATE_KEY
      identity: #@ data.values.GIT_SSH_PRIVATE_KEY
      identity_pub: #@ data.values.GIT_SSH_PUBLIC_KEY
      known_hosts: #@ data.values.GIT_KNOWN_HOSTS
#@ end

apiVersion: v1
kind: Secret
metadata:
  name: workload-git-auth
  namespace: tap-install
type: Opaque
stringData:
  content.yaml: #@ yaml.encode(config())
    
---