#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

apiVersion: v1
kind: Secret
metadata:
  name: git-https
  namespace: tap-install
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.git.username
  password: #@ data.values.git.password
                                                      