#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ def registry_credentials_config():
#@  return {
#@    "auths": {
#@      data.values.INSTALL_REGISTRY_HOSTNAME: {
#@        "username": data.values.INSTALL_REGISTRY_USERNAME,
#@        "password": data.values.INSTALL_REGISTRY_PASSWORD
#@      }
#@    }
#@  }
#@ end

#! load supply chain registry creds e.g registry.gcp.ellin.net
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: tap-install
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ json.encode(registry_credentials_config())
      
---