#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sso-config-app
  namespace: tanzu-sync
spec:
  serviceAccountName: sync-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: #@ data.values.custom.gitops.url
      ref: #@ data.values.custom.gitops.ref
  template:
  - sops:
    age:
      privateKeysSecretRef:
          name: sync-age-identity
  - ytt:
      paths:
      - clusters/common/app-contents/common/app-sso
      valuesFrom:
       - secretRef:
           name: tanzu-gitops
  deploy:
  - kapp: {}