#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gitops-config-app
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: gitops-config-app/app
    kapp.k14s.io/change-rule: "upsert after upserting tap"
spec:
  serviceAccountName: sync-sa
  syncPeriod: 1m
  fetch:
  - git:
      url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
      ref: origin/main
  template:
  - ytt:
      paths:
      - clusters/appref-view/gitops/app
      valuesFrom:
       - secretRef:
           name: tanzu-gitops
  deploy:
  - kapp: {}