tap_install:
  package_repository:
    oci_repository: tanzu.packages.broadcom.com/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: "1.9.0"
    package_version: "1.9.0"
