---
tap_install:
  values:
    profile: full
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    shared:
      kubernetes_version: "1.29"
      ingress_domain: e2e-build.amer.end2end.link
      ingress_issuer: ""
      image_registry:
        project_path: gcr.io/fe-cpage/tap
      activateAppLiveViewSecureAccessControl: false

    buildservice:
      kp_default_repository: "gcr.io/fe-cpage/build"

    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: contour-tls
        secret_name: tls
      domain: e2e-build.amer.end2end.link
      samples:
        include: true

    appliveview:
      ingressEnabled: true
      tls:
        namespace: contour-tls
        secretName: tls

    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      registry:
        server: "gcr.io/fe-cpage"
        repository: "tap/supply-chain"
      gitops:
        ssh_secret: git-ssh
        username: cpage-pivotal
        branch: main
        commit_message: "Update from TAP Supply Chain Choreographer"
        email: pcorby@vmware.com
        repository_prefix: ssh://git@github.com/cpage-pivotal/

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/e2e-tap-build-cluster/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/tanzu-end-to-end/e2e-tap-gitops
          path: _ytt_lib/namespace-resources
      import_data_values_secrets:
        - name: workload-git-auth
          namespace: tap-install
          create_export: true
        - name: workload-git-token
          namespace: tap-install
          create_export: true
      overlay_secrets:
        - name: workload-git-auth-overlay
          namespace: tap-install
          create_export: true

    contour:
      contour:
        replicas: 3
      envoy:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: '*.e2e-build.amer.end2end.link'
          type: LoadBalancer
        workload:
          type: Deployment
          replicas: 3

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      tls:
        namespace: contour-tls
        secretName: tls
      app_config:
        app:
          baseUrl: https://tap-gui.e2e-build.amer.end2end.link
        auth:
          allowGuestAccess: true
        catalog:
          locations:
            - type: url
              target: https://github.com/cpage-pivotal/spring-sensors/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cpage-pivotal/tanzu-java-web-app/blob/main/catalog-info.yaml
        backend:
          baseUrl: https://tap-gui.e2e-build.amer.end2end.link
          cors:
            origin: https://tap-gui.e2e-build.amer.end2end.link
        kubernetes:
          serviceLocatorMethod:
            type: 'multiTenant'
        techdocs:
          builder: 'external'
          publisher:
            type: 'awsS3'
            awsS3:
              bucketName: e2e-tap-techdocs
              credentials:
                roleArn: arn:aws:iam::377668981663:role/ReadTapTechdocs

    metadata_store:
      app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
      ns_for_export_app_cert: "*"

    grype:
      namespace: "default" # (optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"

    package_overlays:
      - name: cert-manager
        secrets:
          - name: cert-manager-overlay