---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: cdelashmutt@vmware.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: us-east-2
            hostedZoneID: Z058827839E1KJS2IN09B
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: tls-test # contour-tls
spec:
  commonName: "*.e2e-test.amer.end2end.link" # "*.e2e-build.amer.end2end.link"
  dnsNames:
    - "*.e2e-test.amer.end2end.link"
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: tls
  subject:
    organizations:
      - vmware
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: contour-tls
spec:
  delegations:
    - secretName: tls
      targetNamespaces:
        - "*"
