#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bookstore-api-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: bookstore-api-demo
    apps.tanzu.vmware.com/has-tests: "true"
  namespace: canary
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository_name
      value: "trp-gitops-canary"
  build:
    env:
    - name: BP_JVM_VERSION
      value: '17'
  source:
    git:
      url: https://github.com/jeffellin/trp_bookstore_api_demo
      ref:
        branch: main
