apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello
  namespace: test
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: '17'
  source:
    git:
      url: https://github.com/tanzu-end-to-end/trp-tanzu-java-web-app.git
      ref:
        branch: main
