#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
#@ def config():
apix:
 host: "" #! //host name of the api validation gui leave blank for default
 backstage:
  host: "https://tap-gui.view.amer.end2end.link/"
  port: "443"
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: apix-values
  namespace: tap-install
type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())
