#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name:  apix-install
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: apix
    kapp.k14s.io/change-rule.0: "upsert after upserting apix-repo"
    kapp.k14s.io/change-rule.2: "upsert after upserting tap"
spec:
  packageRef:
    refName: apix.apps.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.apix.version
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: apix-values


