apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: csharp-weather
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/has-tests: "true"
  namespace: workloads
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository_name
      value: "trp-gitops-canary"
  source:
    git:
      url: https://github.com/jeffellin/csharp-weather.git
      ref:
        branch: main
