#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tds
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tds-repo
spec:
  fetch:
    imgpkgBundle:
      image: "registry.gcp.ellin.net/tapbits/tds-packages:1.0.2"
      secretRef:
        name: install-registry-dockerconfig
