---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-overlay
  namespace: tap-install
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "cert-manager"}})
    ---
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::377668981663:role/e2e-tap-build-view-cert-manager
