---
apiVersion: v1
kind: Secret
metadata:
  name: grype-package-overlay
  namespace: tap-install
stringData:
  grype-package-overlay.yaml: |
    #@  load("@ytt:overlay", "overlay")
    #@
    #@  def matchGrypeScanners(index, left, right):
    #@    if left["apiVersion"] != "packaging.carvel.dev/v1alpha1" or left["kind"] != "PackageInstall":
    #@      return False
    #@    end
    #@    return "metadata" in left and "name" in left["metadata"] and left["metadata"]["name"].startswith("grype-scanner")
    #@  end

    #@overlay/match by=matchGrypeScanners, expects="0+"
    ---
    metadata:
      annotations:
        #@overlay/match expects="0+"
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: grype-scantemplate-overlay
---
apiVersion: v1
kind: Secret
metadata:
  name: grype-scantemplate-overlay
  namespace: tap-install
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ blob_scans = overlay.subset({"kind": "ScanTemplate", "metadata": {"name": "blob-source-scan-template"}})
    #@ public_source = overlay.subset({"kind": "ScanTemplate", "metadata": {"name": "public-source-scan-template"}})
    #@overlay/match by=overlay.or_op(blob_scans, public_source), expects=2
    ---
    spec:
      template:
        initContainers:
        #@overlay/match by=overlay.subset({"name": "repo"}),expects=1
        - image: gcr.io/pa-cdelashmutt/tanzu-e2e/source-scan-patch:latest
