apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workload-waas
  namespace: workloads
spec:
  deploy:
    - kapp:
        rawOptions:
          - --dangerous-allow-empty-list-of-resources=true
  fetch:
    - git:
        ref: origin/main
        url: https://gitea.workshop.amer.end2end.link/gitea_admin/gitops-workloads
  serviceAccountName: default
  template:
    - ytt: {}
