#apiVersion: with.sql.tanzu.vmware.com/v1
#kind: MySQL
#metadata:
#  name: sensors-mysql
#  namespace: workloads
#spec:
#  databasePodConfig: {}
#  highAvailability:
#    enabled: false
#  imagePullSecretName: registries-credentials
#  persistentVolumeClaimPolicy: Retain
#  proxyPodConfig: {}
#  resources:
#    metrics: {}
#    mysql:
#      limits:
#        cpu: "2"
#        memory: 6Gi
#      requests:
#        cpu: "1"
#        memory: 4Gi
#    mysqlSidecar: {}
#    proxy: {}
#  serviceType: ClusterIP
#  storageSize: 5Gi
#  tls:
#    secret: {}
