apiVersion: ENC[AES256_GCM,data:j8M=,iv:Ckw7K26jjjwm+BXDxth+sB2LxsIQDBZSgdLKy5MQjzQ=,tag:YV8pIDH6OeelrBYNMcm3Ew==,type:str]
kind: ENC[AES256_GCM,data:83UJwUPS+/27,iv:U2r+FlWoXX91eFNPiUJcXMVaeXgg+00j+8zlARMtIKQ=,tag:RjLY0GNeRgKnvX6fma6jHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FYQYY41f10KQWhp0k8RdENm8uw==,iv:ktkDYdFWqu1wx9jOLRRwHClFzC7jqbN9OCE1cgNmqkc=,tag:HTnSPeJ66arE54EfgwZr6g==,type:str]
    namespace: ENC[AES256_GCM,data:FKwRosb27w==,iv:1nNe4BwqJo51yRp2+ZkZ0wv0Tk6SMATe9BEGfQas7zA=,tag:5OZ6vazOvznhOE6gB0ERQA==,type:str]
data:
    seed.js: ENC[AES256_GCM,data:VSFBIV9WIdU9auyxxU6KQ5qnowCJdTxolkn+ZCTh5me2JssJOM4jsuwMXdWB+MtJQ1qHnSfnJsb/dpha6ZOeOxPmYul2JRVeN+X4LBkcE7PS3bs27m377QT0eT3+4cq1Rvnp3iAnSRCJVwAth8UezIo9AKfNJgBbZ1gSLJSyEn35ktDz4WcUHpN2CVHFaaqE9Eps6ow7pCM5HlT6DDswj2apI1J3DOOKv0HLh+1LmPLbjuSW7M5Zq5e+hHs53926mq+OiKxtjqbH9JBK0BvMP4kfIjLwqFnPYG/MrK60S5/KKT+zbQhWhmn4BRGBJli9MChCZ03v9CFT2W8idagPqn35+KHWtVDrWy/Or5g0PG7izeASWIQxV8QrSUNXWNfPqkX+KoFpIH5yk8nJ9ln6w1ILWJqlaxIj8vS9PO92GrLPciRZMjNSC4pUwa5tF9EyvaquV7TNKM4koo4ch1665uhvuRGAxBsFGT72U/pDj2noKsKtB28id0W/sTkWFR+0E4JDGVPeT87Xws8E2f1QmMxdDxUZ66N1ncTlxUnAilazL3EsRrn2uvktA5m1vHCVpz9eEkmsAmeXue2ly2K8UxCrYXAT7hKuj0CmbG0a07cE35E3aaQzAPrX3YO/X7ikAGsVeDJdiMPmZeKkL8UOfz+/pyyj9N7i9ANO4jcao3vSDmAM48i5jBE6FcjyOnITHyusSZF5BgHY0Y//z1h5MJclee7mrxJ4GRQ9gYuVaTBUil17y6u+4z9FL8oJgXynu/FudmEgQAqE5snwTIRE/VBqeCwuX0QRo5FKJDGxd3o7Hx+dTP/zIAXoHIn/SxEsOSAhpc2qABVLbMwZZgTNNbAs/7cAHOpGl9xJwBDNQsUwopK17BgRk/SPmzH8kV8GPA1on4uIUJdOJZ6M0pjP0KRGfdmj0Yw4H4nyKI3xShvKqG2yTXc36UCmclG/i9aOCRYei2+7YOVMWN283gsLHjPCdksoEIktv+0EF3jfPMjtJpJftLRrPENtPInmIrZeAmtkvv3UI/TtcuxItRbLlOx2WbNKNRJ8NFhdLAU94si8473TysbyGSI8YuOSMx4AujDghoXHe/hgyvUazO6jYPd4aLKRpz4/WJdMEdQJKeIB0Ptfo49t2HIe512T8ZdWnmq00d9PTSxVfQkAfKufu2b1Qs6cucs1OWjTsF8sMa3etu1d6ejfHYSlWvgKeIPLrq1i2fXFGqZy5RZJkKmncOhl/pyB4XyIqXvw4nsmxidpoASTYM4BwAB4lDVrxycAyDSod6UEro4nP+Iz4g==,iv:c257Log/K3ei1svoymlE6BqCYIXsjYzqch6cFn8N/8E=,tag:23c2oAUYUO6LtLw0c2SLXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0jq2plycmkw4l38aak9cth6v4xvn3wp0kgyj0m0da086ygv2clstfn25y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmhXZTBaWWVMY2t1V1NJ
            MldqcWF0Mzk3b0JSQ1p0NjV0OUlLSFZNaFVJCllZK3V4RlpNM0NUN1krbUNWRXpr
            LzZoWWlDaXNqZlM1VVBDdFJIR3Rzdk0KLS0tIDArVGNqcEdCbkJMTUR2Y1RwVjdj
            ZUpWdThEelpLS2JORFp1NDJURnJ2NDQKk2IrEMxYXcP0+1gJi0Bs49yJamNPFCBg
            s3TV49LrOkzrenVkdCGbED0hjozQnR7VrloO1gWUNc9MVGQRha0pSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T19:50:14Z"
    mac: ENC[AES256_GCM,data:yiqP0MW3J2bPRT4f+TTPJhZV24t9UwcQYJaNT2elfihqj4aV6209gfZcmzNNxHk0bC3R+oc5T8xtxDZKCwPVWN8lQUNIX4sm1D0BbB/IPz6wJMrUswmOmARKFff+K4+UP6KE8RlMR7snrd3mSM/B8Z4uaJRt+5p3zsUMj2tHNJU=,iv:+tPgSLJhrowmh8Wko2JiagbziGbdC6e070POTX8E+Nk=,tag:o0xYsli1qztiOAompqQe4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
