apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: FRONTEND_ADDR
          value: shopping:3000
        image: docker.io/vmwareallspark/acme-load-gen:latest
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8089
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo -e "http://nl.alpinelinux.org/alpine/v3.5/main\nhttp://nl.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories
        - set -x;  apk update ; apk add curl && until timeout -t 2 curl -f "http://${FRONTEND_ADDR}";
          do echo "waiting for http://${FRONTEND_ADDR}"; sleep 2; done;
        env:
        - name: FRONTEND_ADDR
          value: shopping:3000
        image: alpine:3.7
        imagePullPolicy: IfNotPresent
        name: wait-frontend
      restartPolicy: Always