apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-test
  namespace: workloads
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: spring-sensors
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://gitea.workshop.amer.end2end.link/gitea_admin/pcorby-1684438690-w01-s001-1684438744.git
      ref:
        branch: main
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: sensors-mysql
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository
      value: ssh://git@github.com/cpage-pivotal/tap-gitops
    - name: gitops_branch
      value: spring-sensors-test