#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def overlay_data():
#@   annotations = { "eks.amazonaws.com/role-arn:": data.values.tap_install.custom.aws.arn}
#@   return {"metadata": {"annotations": annotations}}
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tapgui-manager-overlay
  namespace: tap-install
type: Opaque
stringData:
  #@yaml/text-templated-strings
  overlay.yaml: |-
    #@load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "tap-gui"}})
    ---
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::377668981663:role/appref1-read-techdocs