---
tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'

    shared:
      ingress_domain: "INGRESS-DOMAIN"
      ingress_issuer: # Optional, can denote a cert-manager.io/v1/ClusterIssuer of your choice. Defaults to "tap-ingress-selfsigned".

      image_registry:
        project_path: gcr.io/fe-cpage/tap
#        secret:
#          name: "KP-DEFAULT-REPO-SECRET"
#          namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

#      kubernetes_distribution: "K8S-DISTRO" # Only required if the distribution is OpenShift and must be used with the following kubernetes_version key.

#      kubernetes_version: "K8S-VERSION" # Required regardless of distribution when Kubernetes version is 1.25 or later.

#      ca_cert_data: | # To be passed if using custom certificates.
#        -----BEGIN CERTIFICATE-----
#        MIIFXzCCA0egAwIBAgIJAJYm37SFocjlMA0GCSqGSIb3DQEBDQUAMEY...
#        -----END CERTIFICATE-----

    supply_chain: basic # Can take testing, testing_scanning.

    ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
      registry:
        server: "gcr.io/fe-cpage" # Takes the value from the shared section by default, but can be overridden by setting a different value.
        repository: "tap/supply-chain" # Takes the value from the shared section by default, but can be overridden by setting a different value.
      gitops:
        ssh_secret: "git-ssh" # Takes "" as value by default; but can be overridden by setting a different value.

    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    buildservice:
      # Takes the value from the shared section by default, but can be overridden by setting a different value.
      kp_default_repository: "gcr.io/fe-cpage/build"
#      kp_default_repository_secret: # Takes the value from the shared section above by default, but can be overridden by setting a different value.
#        name: "KP-DEFAULT-REPO-SECRET"
#        namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

    tap_gui:
      service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
      metadataStoreAutoconfiguration: true # Create a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/cpage-pivotal/spring-sensors/blob/main/catalog/catalog-info.yaml

    metadata_store:
#      ns_for_export_app_cert: "MY-DEV-NAMESPACE"
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    scanning:
      metadataStore:
        url: "" # Configuration is moved, so set this string to empty.

    grype:
      namespace: "default"
      targetImagePullSecret: "registry-credentials"
      # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
#    tap_telemetry:
#      customer_entitlement_account_number: "CUSTOMER-ENTITLEMENT-ACCOUNT-NUMBER" # (Optional) Identify data for creating the Tanzu Application Platform usage reports.